### ISSUE TITLE
Add new features to the README

### ISSUE THREAD

**Issue by danielcompton** [jonase/kibit#111]
When 0.1.0 is released, we'll need to add documentation for some features. This includes:

- [x] Non-zero exit codes #88 
- [x] Support for clojurescript, cljx, e.t.c. #102 
- [x] Running kibit without project.clj #27
- [x] Add instructions for using with lein-auto

**Comment by danielcompton** [comment]
Pull request is ready, waiting for 0.1.0 to be released.
